USE Insa4_JSA_hacksim_5;


DROP TABLE TB_USER;
DROP TABLE TB_TEST;
DROP TABLE TB_RESULT;
DROP TABLE TB_LANG;
DROP TABLE TB_ARENAROOM;
DROP TABLE TB_CHATROOM;
DROP TABLE ARENA_USER;
DROP TABLE CHAT_USER;

TRUNCATE TB_ARENAROOM;
TRUNCATE ARENA_USER;

TRUNCATE TB_CHATROOM;
TRUNCATE CHAT_USER;


/*********** 테이블 생성 *************/
# 유저정보 테이블
CREATE TABLE TB_USER (
      USER_ID        VARCHAR(20)                    COMMENT '회원ID'
     , USER_PW        VARCHAR(100) NOT NULL          COMMENT '회원PW'
     , USER_NAME      VARCHAR(10)  NOT NULL          COMMENT '회원이름'
     , USER_NICK      VARCHAR(20)  NOT NULL          COMMENT '회원닉네임'
     , USER_LEVEL     VARCHAR(20)  NOT NULL          COMMENT '회원레벨'
     , USER_MENTORING VARCHAR(20)  NOT NULL          COMMENT '멘토멘티'
     , JOIN_DT    DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '가입일'
               );

# 문제 테이블
CREATE TABLE TB_TEST (
      TEST_NUMBER     INT       NOT NULL    COMMENT '문제번호'
    , TEST_NAME   VARCHAR(20)   NOT NULL    COMMENT '문제이름'
     , TEST_DES    VARCHAR(1000) NOT NULL    COMMENT '문제정보'
               );
                    
# 문제입출력정보
CREATE TABLE TB_RESULT (
      RESULT_NUMBER     INT      NOT NULL   COMMENT '일련번호'
    , TEST_NUMBER       INT      NOT NULL   COMMENT '문제번호FK'
     , RESULT_INPUT  VARCHAR(100) NOT NULL   COMMENT '입력값'
     , RESULT_OUTPUT VARCHAR(100) NOT NULL   COMMENT '출력값'
                  );
                        
# 사용자 사용언어
CREATE TABLE TB_LANG (
      USER_ID VARCHAR(20)         COMMENT '회원ID'
    , LANG_SKILL  VARCHAR(20)  NOT NULL COMMENT '사용가능언어'
               );

# CODE ARENA 채팅방 정보
CREATE TABLE TB_ARENAROOM (
      ROOM_NUMBER  INT    PRIMARY KEY  NOT NULL   COMMENT '번호'
    , ROOM_NAME    VARCHAR(20)         NOT NULL   COMMENT '방이름'
     , ROOM_LANG    VARCHAR(20)         NOT NULL   COMMENT '개발언어'
     , ROOM_HOST    VARCHAR(20)         NOT NULL   COMMENT '작성자'
     , USER_COUNT   INT                 NOT NULL   COMMENT '접속 유저수'
                            );

# CODE Chat 채팅방 정보
CREATE TABLE TB_CHATROOM (
      ROOM_NUMBER  INT          PRIMARY KEY     NOT NULL   COMMENT '번호'
    , ROOM_METHOD  VARCHAR(20)                  NOT NULL   COMMENT '채팅방식'
    , ROOM_NAME    VARCHAR(20)                  NOT NULL   COMMENT '방이름'
     , ROOM_LANG    VARCHAR(20)                  NOT NULL   COMMENT '개발언어'
     , ROOM_HOST    VARCHAR(20)                  NOT NULL   COMMENT '작성자'
     , USER_COUNT   INT           NOT NULL   COMMENT '접속 유저수'
                            );
                            
CREATE TABLE ARENA_USER (
      ROOM_NUMBER   INT   NOT NULL  COMMENT '번호'
    , CONN_USER     VARCHAR(20)   NOT NULL  COMMENT '접속유저'
     , USER_READY    VARCHAR(20)   DEFAULT 'N' NOT NULL  COMMENT '유저 READY 유무'
                  );

CREATE TABLE CHAT_USER (
      ROOM_NUMBER   INT   NOT NULL  COMMENT '번호'
    , CONN_USER     VARCHAR(20)   NOT NULL  COMMENT '접속유저'
     , SOCKET_ID     VARCHAR(100)  NOT NULL  COMMENT '소켓아이디'
                  );
/************* 테이블 생성 끝 **************/

/************* 테이블 제약조건 **************/
ALTER TABLE TB_USER ADD CONSTRAINT PK_ID PRIMARY KEY(USER_ID);
ALTER TABLE TB_TEST ADD CONSTRAINT PK_NUMBER PRIMARY KEY(TEST_NUMBER);
ALTER TABLE TB_RESULT ADD CONSTRAINT PK_RESULT PRIMARY KEY(RESULT_NUMBER);
ALTER TABLE TB_RESULT ADD CONSTRAINT FK_NUMBER FOREIGN KEY(TEST_NUMBER) REFERENCES TB_TEST(TEST_NUMBER);
ALTER TABLE TB_LANG ADD CONSTRAINT FK_ID FOREIGN KEY(USER_ID) REFERENCES TB_USER(USER_ID);

ALTER TABLE ARENA_USER ADD CONSTRAINT FK_ROOMNUM FOREIGN KEY(ROOM_NUMBER) REFERENCES TB_ARENAROOM(ROOM_NUMBER);
ALTER TABLE CHAT_USER ADD CONSTRAINT FK_CHATROOMNUM FOREIGN KEY(ROOM_NUMBER) REFERENCES TB_CHATROOM(ROOM_NUMBER);

ALTER TABLE TB_TEST MODIFY TEST_NUMBER INT NOT NULL AUTO_INCREMENT;
ALTER TABLE TB_RESULT MODIFY RESULT_NUMBER INT NOT NULL AUTO_INCREMENT;
/************* 테이블 제약조건 끝 **************/


